                <i class="em em-blush" id="blush" onclick="showThisEmoji(this)"></i>
                <i class="em em-confused" id="confused" onclick="showThisEmoji(this)"></i>
                <i class="em em-astonished" id="astonished" onclick="showThisEmoji(this)"></i>
                <i class="em em-angry" id="angry" onclick="showThisEmoji(this)"></i>
                <i class="em em-cold_sweat" id="cold_sweat" onclick="showThisEmoji(this)"></i>
                <i class="em em-cry" id="cry" onclick="showThisEmoji(this)"></i>
                <i class="em em-disappointed" id="disappointed" onclick="showThisEmoji(this)"></i>
                <i class="em em-disappointed_relieved" id="disappointed_relieved" onclick="showThisEmoji(this)"></i>
                <i class="em em-disappointed" id="disappointed" onclick="showThisEmoji(this)"></i>
                <i class="em em-dizzy_face" id="dizzy_face" onclick="showThisEmoji(this)"></i>
                <i class="em em-expressionless" id="expressionless" onclick="showThisEmoji(this)"></i>
                <i class="em em-fearful" id="fearful" onclick="showThisEmoji(this)"></i>
                <i class="em em-broken_heart" id="broken_heart" onclick="showThisEmoji(this)"></i>
                <i class="em em-cupid" id="cupid" onclick="showThisEmoji(this)"></i>
                <i class="em em-heart" id="heart" onclick="showThisEmoji(this)"></i>
                <i class="em em-heartpulse"  id="heartpulse" onclick="showThisEmoji(this)"></i>
                <i class="em em-heartbeat" id="heartbeat" onclick="showThisEmoji(this)"></i>
                <i class="em em-kissing_heart" id="kissing_heart" onclick="showThisEmoji(this)"></i>
                <i class="em em-yellow_heart" id="yellow_heart" onclick="showThisEmoji(this)"></i>
                <i class="em em-green_heart" id="green_heart" onclick="showThisEmoji(this)"></i>
                <i class="em em-heart_decoration" id="heart_decoration" onclick="showThisEmoji(this)"></i>
                <i class="em em-couplekiss" id="couplekiss" onclick="showThisEmoji(this)"></i>
                <i class="em em-bowtie" id="bowtie" onclick="showThisEmoji(this)"></i>
                <i class="em em-frowning" id="frowning" onclick="showThisEmoji(this)"></i>
                <i class="em em-flushed" id="flushed" onclick="showThisEmoji(this)"></i>
                <i class="em em-grimacing" id="grimacing" onclick="showThisEmoji(this)"></i>
                <i class="em em-grinning" id="grinning" onclick="showThisEmoji(this)"></i>
                <i class="em em-frowning" id="frowning" onclick="showThisEmoji(this)"></i>
                <i class="em em-grin" id="grin" onclick="showThisEmoji(this)"></i>
                <i class="em em-heart_eyes" id="heart_eyes" onclick="showThisEmoji(this)"></i>
                <i class="em em-imp" id="imp" onclick="showThisEmoji(this)"></i>
                <i class="em em-innocent" id="innocent" onclick="showThisEmoji(this)"></i>
                <i class="em em-joy" id="joy" onclick="showThisEmoji(this)"></i>
                <i class="em em-hushed" id="hushed" onclick="showThisEmoji(this)"></i>
                <i class="em em-kissing_closed_eyes" id="kissing_closed_eyes" onclick="showThisEmoji(this)"></i>
                <i class="em em-kissing_smiling_eyes" id="kissing_smiling_eyes" onclick="showThisEmoji(this)"></i>
                <i class="em em-kissing" id="kissing" onclick="showThisEmoji(this)"></i>
                <i class="em em-kissing_face" id="kissing_face" onclick="showThisEmoji(this)"></i>
                <i class="em em-laughing" id="laughing" onclick="showThisEmoji(this)"></i>
                <i class="em em-mask" id="mask" onclick="showThisEmoji(this)"></i>
                <i class="em em-neutral_face" id="neutral_face" onclick="showThisEmoji(this)"></i>
                <i class="em em-no_mouth" id="no_mouth" onclick="showThisEmoji(this)"></i>
                <i class="em em-open_mouth" id="open_mouth" onclick="showThisEmoji(this)"></i>
                <i class="em em-persevere" id="persevere" onclick="showThisEmoji(this)"></i>
                <i class="em em-pensive" id="pensive" onclick="showThisEmoji(this)"></i>
                <i class="em em-relaxed" id="relaxed" onclick="showThisEmoji(this)"></i>
                <i class="em em-relieved" id="relieved" onclick="showThisEmoji(this)"></i>
                <i class="em em-satisfied" id="satisfied" onclick="showThisEmoji(this)"></i>
                <i class="em em-sleeping" id="sleeping" onclick="showThisEmoji(this)"></i>
                <i class="em em-sleepy" id="sleepy" onclick="showThisEmoji(this)"></i>
                <i class="em em-smile" id="smile" onclick="showThisEmoji(this)"></i>
                <i class="em em-smiley" id="smiley" onclick="showThisEmoji(this)"></i>
                <i class="em em-smirk" id="smirk" onclick="showThisEmoji(this)"></i>
                <i class="em em-stuck_out_tongue_closed_eyes" id="stuck_out_tongue_closed_eyes" onclick="showThisEmoji(this)"></i>
                <i class="em em-stuck_out_tongue_winking_eye" id="stuck_out_tongue_winking_eye" onclick="showThisEmoji(this)"></i>
                <i class="em em-stuck_out_tongue" id="stuck_out_tongue" onclick="showThisEmoji(this)"></i>
                <i class="em em-sunglasses" id="sunglasses" onclick="showThisEmoji(this)"></i>
                <i class="em em-sweat_smile" id="sweat_smile" onclick="showThisEmoji(this)"></i>
                <i class="em em-sweat" id="sweat" onclick="showThisEmoji(this)"></i>
                <i class="em em-tired_face" id="tired_face" onclick="showThisEmoji(this)"></i>
                <i class="em em-triumph" id="triumph" onclick="showThisEmoji(this)"></i>
                <i class="em em-unamused" id="unamused" onclick="showThisEmoji(this)"></i>
                <i class="em em-weary" id="weary" onclick="showThisEmoji(this)"></i>
                <i class="em em-wink" id="wink" onclick="showThisEmoji(this)"></i>
                <i class="em em-worried" id="worried" onclick="showThisEmoji(this)"></i>